#ifndef TOML_PREDEFINE_HPP
#define TOML_PREDEFINE_HPP

#ifndef BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS
#define BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS
#endif

#ifndef BOOST_MPL_LIMIT_METAFUNCTION_ARITY
#define BOOST_MPL_LIMIT_METAFUNCTION_ARITY 20
#endif

#endif// TOML_PREDEFINE_HPP
